{
 "title": "CloudStack Metrics",
 "description": "CollectD & Graphite Server Metrics Dashboard for CloudStack",
 "tags": [ "collectd" ],
 "time": { "from": "now-1h", "to": "now" },
 "templating": {
  "list": [
   { "name": "prefix", "query": "${VAR_PREFIX}" },
   { "name": "server", "query": "$prefix.*" }
  ]
 },
 "panels": [
  {
   "title": "Allocalted CPU",
   "type": "grafana-piechart-panel",
   "gridPos": { "h": 6, "w": 4, "x": 0, "y": 0 },
   "format": "hertz",
   "valueName": "current",
   "targets": [
    {
     "target": "alias(scale(collectdgrafana-vm-01collectd.cloudstack.current-zonecapacity_mg-lgp-01_z_capacity_cpu_free, 1000000), 'Free')"
    },
    {
     "target": "alias(scale(collectdgrafana-vm-01collectd.cloudstack.current-zonecapacity_mg-lgp-01_z_capacity_cpu_used, 1000000), 'Used')"
    }
   ]
  },
  {
   "title": "Allocalted Memory",
   "type": "grafana-piechart-panel",
   "gridPos": { "h": 6, "w": 5, "x": 4, "y": 0 },
   "format": "decbytes",
   "valueName": "current",
   "targets": [
    {
     "target": "alias(collectdgrafana-vm-01collectd.cloudstack.current-zonecapacity_mg-lgp-01_z_capacity_memory_free, 'Free')"
    },
    {
     "target": "alias(collectdgrafana-vm-01collectd.cloudstack.current-zonecapacity_mg-lgp-01_z_capacity_memory_used, ' Used')"
    },
    {}
   ]
  },
  {
   "title": "Allocated Disk",
   "type": "grafana-piechart-panel",
   "gridPos": { "h": 6, "w": 5, "x": 9, "y": 0 },
   "format": "decbytes",
   "valueName": "current",
   "targets": [
    {
     "target": "alias(collectdgrafana-vm-01collectd.cloudstack.current-zonecapacity_mg-lgp-01_z_capacity_allocated_disk_free, 'Free ')"
    },
    {
     "target": "alias(collectdgrafana-vm-01collectd.cloudstack.current-zonecapacity_mg-lgp-01_z_capacity_allocated_disk_used, 'Used ')"
    }
   ]
  },
  {
   "title": "Allocalted Secondary Storage",
   "type": "grafana-piechart-panel",
   "gridPos": { "h": 6, "w": 5, "x": 14, "y": 0 },
   "format": "decbytes",
   "valueName": "current",
   "targets": [
    {
     "target": "alias(collectdgrafana-vm-01collectd.cloudstack.current-zonecapacity_mg-lgp-01_z_capacity_SSdisk_free, 'Free ')"
    },
    {
     "target": "alias(collectdgrafana-vm-01collectd.cloudstack.current-zonecapacity_mg-lgp-01_z_capacity_SSdisk_used, 'Used ')"
    }
   ]
  },
  {
   "title": "Allocalted IP Address",
   "type": "grafana-piechart-panel",
   "gridPos": { "h": 6, "w": 5, "x": 19, "y": 0 },
   "format": "short",
   "valueName": "current",
   "targets": [
    {
     "target": "alias(collectdgrafana-vm-01collectd.cloudstack.current-zonecapacity_mg-lgp-01_z_capacity_public_ip_free, 'Free ')"
    },
    {
     "target": "alias(collectdgrafana-vm-01collectd.cloudstack.current-zonecapacity_mg-lgp-01_z_capacity_public_ip_used, 'Used ')"
    }
   ]
  },
  {
   "title": "Used CPU",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 4, "x": 0, "y": 6 },
   "format": "percent",
   "valueName": "avg",
   "targets": [
    {
     "target": "alias(collectdgrafana-vm-01collectd.cloudstack.current-zonecapacity_mg-lgp-01_z_capacity_cpu_percent-used, 'CPU avg')"
    }
   ]
  },
  {
   "title": "Used Memory",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 5, "x": 4, "y": 6 },
   "format": "percent",
   "valueName": "current",
   "targets": [
    {
     "target": "collectdgrafana-vm-01collectd.cloudstack.current-zonecapacity_mg-lgp-01_z_capacity_memory_percent-used"
    }
   ]
  },
  {
   "title": "Used Disk",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 5, "x": 9, "y": 6 },
   "format": "percent",
   "valueName": "avg",
   "targets": [
    {
     "target": "alias(collectdgrafana-vm-01collectd.cloudstack.current-zonecapacity_mg-lgp-01_z_capacity_allocated_disk_percent-used, 'Accounts')"
    }
   ]
  },
  {
   "title": "Used Secondary Storage",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 5, "x": 14, "y": 6 },
   "format": "percent",
   "valueName": "avg",
   "targets": [
    {
     "target": "alias(collectdgrafana-vm-01collectd.cloudstack.current-zonecapacity_mg-lgp-01_z_capacity_SSdisk_percent-used, 'CPU avg')"
    }
   ]
  },
  {
   "title": "Used Public IP",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 5, "x": 19, "y": 6 },
   "format": "percent",
   "valueName": "avg",
   "targets": [
    {
     "target": "alias(collectdgrafana-vm-01collectd.cloudstack.current-zonecapacity_mg-lgp-01_z_capacity_public_ip_percent-used, 'Accounts')"
    }
   ]
  },
  {
   "title": "CPU Total",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 4, "x": 0, "y": 9 },
   "format": "hertz",
   "valueName": "avg",
   "targets": [
    {
     "target": "scale(collectdgrafana-vm-01collectd.cloudstack.current-zonecapacity_mg-lgp-01_z_capacity_cpu_total, 1000000)"
    }
   ]
  },
  {
   "title": "Memory Total",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 5, "x": 4, "y": 9 },
   "format": "decbytes",
   "valueName": "avg",
   "targets": [
    {
     "target": "collectdgrafana-vm-01collectd.cloudstack.current-zonecapacity_mg-lgp-01_z_capacity_memory_total"
    }
   ]
  },
  {
   "title": "Disk Total",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 5, "x": 9, "y": 9 },
   "format": "decbytes",
   "valueName": "avg",
   "targets": [
    {
     "target": "collectdgrafana-vm-01collectd.cloudstack.current-zonecapacity_mg-lgp-01_z_capacity_allocated_disk_total"
    }
   ]
  },
  {
   "title": "Secondary Storage Total",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 5, "x": 14, "y": 9 },
   "format": "decbytes",
   "valueName": "avg",
   "targets": [
    {
     "target": "alias(collectdgrafana-vm-01collectd.cloudstack.current-zonecapacity_mg-lgp-01_z_capacity_SSdisk_total, 'Accounts')"
    }
   ]
  },
  {
   "title": "Public IP Total",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 3, "x": 20, "y": 9 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "target": "collectdgrafana-vm-01collectd.cloudstack.current-zonecapacity_mg-lgp-01_z_capacity_public_ip_total"
    }
   ]
  }
 ]
}